from slack_sdk.errors import SlackApiError


def update_message_ferramentas(event, ack, say, logger, body, client):
    ack()
    event = body["message"]
    channel_id = body["channel"]["id"]
    thread_ts = event.get("ts", None)
    name = body["user"]["id"]
    text_user = f"*<@{name}>, selecione a ferramenta onde voce possuí dúvidas sobre o processo.*"

    try:
        result = client.chat_update(channel=channel_id,
                                    ts=thread_ts,
                                    blocks=[{"type": "actions",
                                             "block_id": "go_back",
                                             "elements": [{"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": " ↩ Voltar ao Início"},
                                                           "action_id": "go_back",
                                                           },
                                                          ]},
                                            {"type": "section",
                                             "text": {"type": "mrkdwn",
                                                      "text": text_user}},
                                            {"type": "divider"},
                                            {"type": "actions",
                                             "block_id": "docs_suporte1",
                                             "elements": [{"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "E-mail"},
                                                           "action_id": "email",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Power BI"},
                                                           "action_id": "powerbi",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "LeadBroker"},
                                                           "action_id": "leadbroker",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "V4 Academy"},
                                                           "action_id": "v4academy",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Edu V4"},
                                                           "action_id": "eduv4",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          ]},
                                            {"type": "actions",
                                             "block_id": "docs_suporte2",
                                             "elements": [{"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Marketing Lab"},
                                                           "action_id": "mktlab",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Lab Financeiro"},
                                                           "action_id": "labfinanceiro",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Unbounce"},
                                                           "action_id": "unbounce",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Zapier"},
                                                           "action_id": "zapier",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "G4 Skills"},
                                                           "action_id": "g4skills",
                                                           "style": "danger",
                                                           "url": "URL"},
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Stack Digital"},
                                                           "action_id": "stack_digital",
                                                           "style": "danger",
                                                           },
                                                          ]},
                                            {"type": "divider"},
                                            {"type": "section",
                                             "text": {"type": "mrkdwn",
                                                      "text": "*Isso foi o suficiente para te ajudar?*"}},
                                            {"type": "actions",
                                             "block_id": "submitBlock",
                                             "elements": [{"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Sim"},
                                                           "style": "primary",
                                                           "value": "submitSim",
                                                           "action_id": "submitSim",
                                                           },
                                                          {"type": "button",
                                                           "text": {"type": "plain_text",
                                                                    "text": "Não"},
                                                           "style": "danger",
                                                           "value": "submitNao",
                                                           "action_id": "submitNao",
                                                           },
                                                          ]}],
                                    thread_ts=thread_ts)
        logger.info(result)

    except SlackApiError as e:
        logger.error(f"Error: {e}")
